//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrubCaddie.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GolfCourse
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public string Lon { get; set; }
        public string Lat { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> Profile_Id { get; set; }
    
        public virtual Profile Profile { get; set; }
    }
}
