//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrubCaddie.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public string ImageSource { get; set; }
        public string Notes { get; set; }
        public int Size { get; set; }
        public double Price { get; set; }
        public byte[] Image { get; set; }
        public string ImageFileType { get; set; }
        public string ImageCaption { get; set; }
        public Nullable<int> Menu_Id { get; set; }
    
        public virtual Menu Menu { get; set; }
    }
}
