//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrubCaddie.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int Id { get; set; }
        public int ProfileId { get; set; }
        public double Cost { get; set; }
        public string Lat { get; set; }
        public string Lon { get; set; }
    
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
