//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrubCaddie.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public Profile()
        {
            this.GolfCourses = new HashSet<GolfCourse>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int LoginId { get; set; }
    
        public virtual ICollection<GolfCourse> GolfCourses { get; set; }
        public virtual Login Login { get; set; }
    }
}
